# version: 2.1

# jobs:
#  build:
#    docker:
#      - image: cimg/node:18.14.2
#    steps:
#      - checkout
#      - run: node test1.cy.js

# workflows:
#   build_now:
#     jobs:
#       - build    
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.14.2
    steps:
      - checkout
      - run: npm install cypress
      - run: npx cypress run

workflows:
  version: 2
  build_now:
    jobs:
      - build

